### ISSUE TITLE
ensert math expressions by buttons like calculator

### ISSUE THREAD

**Issue by amanborka** [LeoDog896/svelte-mathquill#1]
Hello dear! Thank you very much for making this package.
Secondly, I had a question, which method should I use if I want to enter equations using the buttons like a calculator?
Thank

**Comment by tristan-f-r** [comment]
Good question! When I was making this library, I never planned for external input - I'll get back to you in a bit to see if the method already exists here or needs some extra API bindings.

**Comment by amanborka** [comment]
> Good question! When I was making this library, I never planned for external input - I'll get back to you in a bit to see if the method already exists here or needs some extra API bindings.

Thank you very much for answering me.
I apologize for my bad English

**Comment by amanborka** [comment]
For example, the code below is made in pure html :

`<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="rec\mathquill.css">
  <script src="rec\jquery.min.js"></script>
  <title>Document</title>
</head>

<body>

  <div class="container">
    <script src="rec\mathquill.js"></script>
  <p>Type math here: <span id="math-field"></span></p>
  <div id="keyboard">
    <div class="btn-group" role="group" aria-label="math functions">
      <button type="button" class="btn btn-default" onClick='input("\\sqrt")'>√</button>
      <button type="button" class="btn btn-default" onClick='input("\\sin")'>sin</button>
      <button type="button" class="btn btn-default" onClick='input("\\cos")'>cos</button>
      <button type="button" class="btn btn-default" onClick='input("\\tan")'>tan</button>
      <button type="button" class="btn btn-default" onClick='input("\\root")'>Root</button>
    </div>
  </div>

  </div>

  <script>
    var mathFieldSpan = document.getElementById('math-field');
    var MQ = MathQuill.getInterface(2);
    var mathField = MQ.MathField(mathFieldSpan, {
      spaceBehavesLikeTab: true,
      handlers: {
        edit: function () {
          mathField.focus()
        }
      }
    });

    function input(str) {
      mathField.cmd(str)
      mathField.focus()
    }
  </script>

</body>

</html>`

**Comment by tristan-f-r** [comment]
Thanks! `cmd` was the missing function, I'll bind it really quickly! Also, I'll export the main mathquill function if I forget this in the future.

**Comment by tristan-f-r** [comment]
Published! 0.7.0 comes with an extra `cmd` function binding as well as a new function, `mathQuillInstance`, that returns the current math quill instance in case you need to tweak it further.

**Comment by amanborka** [comment]
> Published! 0.7.0 comes with an extra `cmd` function binding as well as a new function, `mathQuillInstance`, that returns the current math quill instance in case you need to tweak it further.

Thank you very much
