### ISSUE TITLE
I could not use this cmd function

### ISSUE THREAD

**Issue by amanborka** [LeoDog896/svelte-mathquill#2]
I apologize for bothering you so often
Now how to use this cmd???

`<MathQuill bind:latex autofocus={true} />`

**Comment by tristan-f-r** [comment]
Absolutely! I never added any documentation on the command, but you need to bind the self element to call the function there, e.g:

```svelte
<script>
  let quill; // now you can do quill.cmd()
</script>

<MathQuill bind:this={quill} bind:latex autofocus={true} />
```

**Comment by amanborka** [comment]
> Absolutely! I never added any documentation on the command, but you need to bind the self element to call the function there, e.g:
> 
> ```svelte
> <script>
>   let quill; // now you can do quill.cmd()
> </script>
> 
> <MathQuill bind:this={quill} bind:latex autofocus={true} />
> ```

thanks a lot
This worked
