### ISSUE TITLE
focus mode

### ISSUE THREAD

**Issue by amanborka** [LeoDog896/svelte-mathquill#3]
Of course, sorry, I have a suggestion for you after clicking the button when the mathematical expression is entered, it is not good to stay in the focus mode?

I have added a localy and if you like it, please add it too

`function input(str) {
      mathField.cmd(str)
      mathField.focus()
    }`

**Comment by tristan-f-r** [comment]
I do want to make this library a wrapper for MathQuill and not add anything too much to it. I would probably add it if the utility had substantial size, but given the process to run two commands it seems better to run them explicitly.

**Comment by amanborka** [comment]
> I do want to make this library a wrapper for MathQuill and not add anything too much to it. I would probably add it if the utility had substantial size, but given the process to run two commands it seems better to run them explicitly.

That's right, my dear, thank you very much
